apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: jukki90/k8lessons:lesson2
          name: web
          volumeMounts:
            - name: app
              mountPath: /app
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /index.html
              port: 8000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 8000
      initContainers:
        - name: web-init
          image: busybox:1.32.1
          volumeMounts:
            - name: app
              mountPath: /app
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumes:
        - name: app
          emptyDir: {}