apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: jukki90/paymentservice:v0.0.2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"